<a href="https://colab.research.google.com/github/dr-koehler-ai/numpy-practice/blob/main/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

heart_rate = [85, 92, 101, 115, 130]
#mean heart rate
print(sum(heart_rate)/len(heart_rate))
# maximum heart rate
print(max(heart_rate))
# min heart rate
print(min(heart_rate))

array = np.array(heart_rate)
print(np.mean(array)) # mean heart rate
print(np.max(array)) # maximum heart rate
print(np.min(array)) # min heart rate
print(np.std(array)) # standard deviation

104.6
130
85
104.6
130
85
16.181470884935027


In [ ]:
import numpy as np

heart_rate = np.array([85, 92, 101, 115, 130])
rr = np.array([70, 82, 91, 105, 130])

def risk_mask(arr1, arr2):
  high_heart_rate = np.array([])
  high_rr = np.array([])
  for i in range(len(arr1)):
    if arr1[i] > 100:
      high_heart_rate = np.append(high_heart_rate, arr1[i])
  for i in range(len(arr2)):
    if arr2[i] < 90:
      high_rr = np.append(high_rr, arr2[i])
  return high_heart_rate, high_rr

print(risk_mask(heart_rate, rr))

(array([101., 115., 130.]), array([70., 82.]))


In [ ]:
import numpy as np

heart_rate = np.array([85, 92, 101, 115, 130])
rr = np.array([70, 82, 91, 105, 130])

risk_mask = (heart_rate > 100) | (rr < 90)

print(risk_mask)


[ True  True  True  True  True]


In [ ]:
import numpy as np

#100 Patienten mit zufälligen: Herzfrequenzen, Blutdrücken, Laktatwerten
rr_heart_rate = np.random.randint(0, 200, size=(100, 2))
lac = np.random.randint(0, 20, size=(100,1))
criteria = np.zeros((100,1))
patients = np.hstack((rr_heart_rate, lac, criteria))
#print(patients)

#Wie viele Patienten haben Tachykardie?
def tachykardie(arr):
  tachykardie = np.array([])
  for i in range(len(arr)):
    if arr[i][0] > 100:
      tachykardie = np.append(tachykardie, arr[i][0])
  return tachykardie
print(len(tachykardie(patients)))

#Wie viele Patienten haben Hypotonie?
def hypotonie(arr):
  hypotonie = np.array([])
  for i in range(len(arr)):
    if arr[i][1] < 90:
      hypotonie = np.append(hypotonie, arr[i][1])
  return hypotonie
print(len(hypotonie(patients)))

#Wie viele Patienten haben Laktat > 2?
def high_laktat(arr):
  high_laktat = np.array([])
  for i in range(len(arr)):
    if arr[i][2] > 2:
      high_laktat = np.append(high_laktat, arr[i][2])
  return high_laktat
print(len(high_laktat(patients)))

#Wie viele erfüllen mindestens zwei Kriterien?
def criteria(arr):
  for i in range(len(arr)):
    if arr[i][0] > 100:
      arr[i][3] += 1
    if arr[i][1] < 90:
      arr[i][3] += 1
    if arr[i][2] > 2:
      arr[i][3] += 1

  many_criteria = np.array([])
  for i in range(len(arr)):
    if arr[i][3] > 1:
      many_criteria = np.append(many_criteria, arr[i][3])
  return len(many_criteria)

print(criteria(patients))




45
42
85
62


In [50]:
import numpy as np

hr = np.array([72, 88, 101, 95, 130, 110])

#Erhöhe alle Werte um 5 (ohne Schleife)
print(hr + 5)
#Berechne den Mittelwert
print(np.mean(hr))
#Gib alle Werte > 100 aus
print(hr[hr > 100] )
#Ersetze alle Werte > 120 durch 120 (Clipping)
hr[hr > 120] = 120
print(hr)

[ 77  93 106 100 135 115]
99.33333333333333
[101 130 110]
[ 72  88 101  95 120 110]


In [77]:
import numpy as np

patients = np.array([
    [80, 120, 1.5],   # HR, RR, Laktat
    [105, 85, 2.1],
    [90, 95, 3.2],
    [130, 110, 0.9]
])

#Extrahiere alle Herzfrequenzen
def heart_rate(arr):
  heart_rate = np.array([])
  for i in range(len(arr)):
    heart_rate = np.append(heart_rate, arr[i][0])
  return heart_rate

  # kürzer
print(patients[:,0])

#Finde alle Patienten mit HR > 100
def tachykardie(arr):
  tachykardie = np.array([])
  for i in range(len(arr)):
    if arr[i][0] > 100:
      tachykardie = np.append(tachykardie, arr[i][0])
  return tachykardie

  #kürzer
print(np.where(patients[:,0] > 100))

#Finde alle Patienten mit Laktat > 2
print(np.where(patients[:,2] > 2))

#Finde Patienten, die BEIDES erfüllen
np.where((patients[:,0] > 100)) and ((patients[:,2] > 2))
import numpy as np

patients = np.array([
    [80, 120, 1.5],   # HR, RR, Laktat
    [105, 85, 2.1],
    [90, 95, 3.2],
    [130, 110, 0.9]
])

#Extrahiere alle Herzfrequenzen
def heart_rate(arr):
  heart_rate = np.array([])
  for i in range(len(arr)):
    heart_rate = np.append(heart_rate, arr[i][0])
  return heart_rate

  # kürzer
print(patients[:,0])

#Finde alle Patienten mit HR > 100
def tachykardie(arr):
  tachykardie = np.array([])
  for i in range(len(arr)):
    if arr[i][0] > 100:
      tachykardie = np.append(tachykardie, arr[i][0])
  return tachykardie

  #kürzer
print(np.where(patients[:,0] > 100))

#Finde alle Patienten mit Laktat > 2
print(patients[(patients[:,0] > 100) & (patients[:,2] > 2)])



[ 80. 105.  90. 130.]
(array([1, 3]),)
(array([1, 2]),)
[ 80. 105.  90. 130.]
(array([1, 3]),)
[[105.   85.    2.1]]


In [58]:
import numpy as np

hr = np.array([80, 110, 130, 90, 150])
rr = np.array([120, 85, 70, 95, 60])
lactate = np.array([1.0, 2.5, 3.0, 0.8, 4.2])

patients = np.concatenate((hr.reshape(5,1), rr.reshape(5,1), lactate.reshape(5,1)), axis=1)
scores = np.zeros(5).reshape(5,1)
patients = np.hstack((patients, scores))

tachy = patients[:,0] > 100
hypo = patients[:,1] < 90
lac = patients[:,2] > 2

score = tachy.astype(int) + hypo.astype(int) + lac.astype(int)

patients[:,3] = score

def risk_class(score):
    if score <= 1:
        return "low"
    elif score == 2:
        return "medium"
    else:
        return "high"

risk_classes = [risc_class(s) for s in patients[:,3]]
patients = np.hstack((patients, np.array(risk_classes).reshape(-1,1)))

print(patients)



[['80.0' '120.0' '1.0' '0.0' 'Low Risk']
 ['110.0' '85.0' '2.5' '3.0' 'High Risk']
 ['130.0' '70.0' '3.0' '3.0' 'High Risk']
 ['90.0' '95.0' '0.8' '0.0' 'Low Risk']
 ['150.0' '60.0' '4.2' '3.0' 'High Risk']]


In [28]:
import numpy as np

np.random.seed(42)
hr = np.random.randint(60, 160, 100)
print(hr)

#Mittelwert, Median, Standardabweichung
print(np.mean(hr))
print(np.median(hr))
print(np.std(hr))

#Minimum, Maximum
print(np.min(hr))
print(np.max(hr))

#Wie viele Patienten sind tachykard (>100)?
tachy = hr > 100

#Wie viele Patienten sind schwer tachykard (>130)
very_tachy = hr > 130

#Berechne Anteil in %
print(sum(tachy)/len(hr)*100)
print(sum(very_tachy)/len(hr)*100)


[111 152  74 131 120  80 142 146 134 134 147 159  83  62  81 112  61 147
  89  97  61 123 119  80  92 135 117  81 148 108 150 118 101 151 119 139
  74 121 121 106 121 110 114 123  62 110  66  80 132  98  77  63 148 119
  73  68 149 112  61 143 151 119 130 103  67 106  94 137 140  95 109  63
  61  65 113  63 113 152 122  77 149 103  93 133 121 159  73 154 107  74
 131 137 146 121  99 144 139 141 112  83]
110.54
113.0
29.278463074417004
61
159
65.0
32.0


In [68]:
import numpy as np
import pandas as pd

url = "https://raw.githubusercontent.com/plotly/datasets/master/diabetes.csv"
data = pd.read_csv(url)

array = data.to_numpy()
print(array.shape)


#Welche Spalte ist der Glukosewert?
print(data.head())

#Finde alle Patienten mit Glukose > 140
high_glucose = array[:,1] > 140

  #oder

hoher_zucker = np.where(array[:,1] > 140)

#Berechne Durchschnitts-Glukose dieser Gruppe

mean_sugar = np.mean(array[:,1])

#Finde Anteil der Patienten mit Outcome = 1
outcome = array[:,8] == 1
print(sum(outcome)/len(array)*100)

#Baue einen einfachen Risiko-Score:
#Glukose > 140 → +1
high_glucose = array[:,1] > 140
#BMI > 30 → +1
high_bmi = array[:,5] > 30
#Alter > 50 → +1
high_age = array[:, 7] > 50

score = high_glucose.astype(int) + high_bmi.astype(int) + high_age.astype(int)

scores = np.zeros(768).reshape(-1,1)
array = np.hstack((array, scores))

array[:,9] = score

def risk_class(score):
    if score <= 1:
        return "low"
    elif score == 2:
        return "medium"
    else:
        return "high"

risk_classes = [risk_class(s) for s in array[:,9]]
array = np.hstack((array, np.array(risk_classes).reshape(-1,1)))

print(array)

(768, 9)
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  
34.89583333333333
[['6.0' '148.0' '72.0' ... '1.0' '2.0' 'medium']
 ['1.0' '85.0' '66.0' ... '0.0' '0.0' 'low']
 ['8.0' '183.0' '64.0' ... '1.0' '1.0' 'low']
 ...
 ['5.0' '121.0' '72.0' ... '0.0' '0.0' 'low']
 ['1.0' '126.0' '60.0' ... '1.0' '1.0' 'low']
 ['1.0' '93.0' '70.0' ... '0.0' '1.0' '